baseURL: "https://joysankar-astro.github.io/" 
title: Joysankar Majummdar
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 

params:
    description: "I am a research assistant (RA) at High Energy Astrophysics Lab, Department of Physics, Banaras Hindu University. My research focuses on temporal, spectral, and multi-wavelength study of blazars."
    author: Joysankar Majumdar
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joysankar Majumdar
          subtitle: "I am a research assistant (RA) at High Energy Astrophysics Lab, Department of Physics, Banaras Hindu University. My research focuses on temporal, spectral, and multi-wavelength study of blazars. I have completed my master's in physics (specialized in Space Physics & Astrophysics) from Banaras Hindu University."
          imageUrl: "joysankar.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:joysanka@bhu.ac.in
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/joysankar-astro

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joysankar M"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
